# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(549, 529)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 59, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(470, 10, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 40, 71, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 40, 61, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 70, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 100, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(0, 130, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(0, 160, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(0, 190, 91, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(390, 10, 59, 15))
        self.label_11.setObjectName("label_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 70, 61, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 100, 61, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 130, 61, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 160, 61, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 190, 61, 23))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(90, 470, 59, 15))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(180, 40, 59, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(300, 10, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(180, 70, 101, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(180, 104, 121, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(180, 140, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(180, 170, 59, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(180, 210, 59, 15))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(300, 40, 59, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(300, 70, 59, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(300, 105, 59, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(300, 140, 59, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(300, 170, 59, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(300, 210, 59, 15))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(390, 40, 59, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(390, 70, 59, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(390, 105, 59, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(390, 140, 59, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(390, 170, 59, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(390, 210, 59, 15))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(470, 40, 59, 15))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(470, 70, 59, 15))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(470, 110, 59, 15))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(470, 140, 59, 15))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setGeometry(QtCore.QRect(470, 170, 59, 15))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(470, 210, 59, 15))
        self.label_37.setObjectName("label_37")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(0, 470, 100, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 490, 100, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 510, 100, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 500, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 500, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 500, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 500, 80, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setGeometry(QtCore.QRect(0, 220, 91, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(0, 250, 91, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(0, 280, 91, 16))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setGeometry(QtCore.QRect(0, 310, 91, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setGeometry(QtCore.QRect(0, 340, 81, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Dialog)
        self.label_43.setGeometry(QtCore.QRect(0, 370, 91, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(Dialog)
        self.label_44.setGeometry(QtCore.QRect(0, 400, 59, 15))
        self.label_44.setObjectName("label_44")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 220, 61, 23))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 250, 61, 23))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 280, 61, 23))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(90, 310, 61, 23))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(90, 340, 61, 23))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(90, 370, 61, 23))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 400, 61, 23))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_45 = QtWidgets.QLabel(Dialog)
        self.label_45.setGeometry(QtCore.QRect(180, 240, 59, 15))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(Dialog)
        self.label_46.setGeometry(QtCore.QRect(180, 270, 59, 15))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setGeometry(QtCore.QRect(300, 240, 59, 15))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(Dialog)
        self.label_48.setGeometry(QtCore.QRect(300, 270, 59, 15))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Dialog)
        self.label_49.setGeometry(QtCore.QRect(390, 240, 59, 15))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(Dialog)
        self.label_50.setGeometry(QtCore.QRect(390, 270, 59, 15))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Dialog)
        self.label_51.setGeometry(QtCore.QRect(470, 240, 59, 15))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Dialog)
        self.label_52.setGeometry(QtCore.QRect(470, 270, 59, 15))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(0, 430, 91, 16))
        self.label_53.setObjectName("label_53")
        self.lineEdit_14 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_14.setGeometry(QtCore.QRect(90, 430, 61, 23))
        self.lineEdit_14.setObjectName("lineEdit_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Компоненты"))
        self.label_2.setText(_translate("Dialog", "Max.%"))
        self.label_3.setText(_translate("Dialog", "Питательность"))
        self.label_4.setText(_translate("Dialog", "Нехватка"))
        self.label_5.setText(_translate("Dialog", "Пшеница"))
        self.label_6.setText(_translate("Dialog", "Ячмень"))
        self.label_7.setText(_translate("Dialog", "Кукурудза"))
        self.label_8.setText(_translate("Dialog", "Мясо/Кос"))
        self.label_9.setText(_translate("Dialog", "Рыбная"))
        self.label_10.setText(_translate("Dialog", "Премикс8184"))
        self.label_11.setText(_translate("Dialog", "Норма"))
        self.label_12.setText(_translate("Dialog", "0%"))
        self.label_13.setText(_translate("Dialog", "КДж"))
        self.label_14.setText(_translate("Dialog", "Получена"))
        self.label_15.setText(_translate("Dialog", "Сырой протеин"))
        self.label_16.setText(_translate("Dialog", "Сырой клетчатки"))
        self.label_17.setText(_translate("Dialog", "Кальций"))
        self.label_18.setText(_translate("Dialog", "Фосфор"))
        self.label_19.setText(_translate("Dialog", "Натрий"))
        self.label_20.setText(_translate("Dialog", "0"))
        self.label_21.setText(_translate("Dialog", "0"))
        self.label_22.setText(_translate("Dialog", "0"))
        self.label_23.setText(_translate("Dialog", "0"))
        self.label_24.setText(_translate("Dialog", "0"))
        self.label_25.setText(_translate("Dialog", "0"))
        self.label_26.setText(_translate("Dialog", "0"))
        self.label_27.setText(_translate("Dialog", "0"))
        self.label_28.setText(_translate("Dialog", "0"))
        self.label_29.setText(_translate("Dialog", "0"))
        self.label_30.setText(_translate("Dialog", "0"))
        self.label_31.setText(_translate("Dialog", "0"))
        self.label_32.setText(_translate("Dialog", "0"))
        self.label_33.setText(_translate("Dialog", "0"))
        self.label_34.setText(_translate("Dialog", "0"))
        self.label_35.setText(_translate("Dialog", "0"))
        self.label_36.setText(_translate("Dialog", "0"))
        self.label_37.setText(_translate("Dialog", "0"))
        self.radioButton.setText(_translate("Dialog", "Утки"))
        self.radioButton_2.setText(_translate("Dialog", "Куры"))
        self.radioButton_3.setText(_translate("Dialog", "Перепела"))
        self.pushButton.setText(_translate("Dialog", "Расчитать"))
        self.pushButton_2.setText(_translate("Dialog", "Сохранить"))
        self.pushButton_3.setText(_translate("Dialog", "Открыть базу"))
        self.pushButton_4.setText(_translate("Dialog", "Выход"))
        self.label_38.setText(_translate("Dialog", "Жмых п-сол."))
        self.label_39.setText(_translate("Dialog", "Шрот соевый"))
        self.label_40.setText(_translate("Dialog", "Мясо/кос/низ"))
        self.label_41.setText(_translate("Dialog", "Яичная мука"))
        self.label_42.setText(_translate("Dialog", "Мука трав."))
        self.label_43.setText(_translate("Dialog", "Масло раст."))
        self.label_44.setText(_translate("Dialog", "Ракушка"))
        self.label_45.setText(_translate("Dialog", "Лизин"))
        self.label_46.setText(_translate("Dialog", "Митионин"))
        self.label_47.setText(_translate("Dialog", "0"))
        self.label_48.setText(_translate("Dialog", "0"))
        self.label_49.setText(_translate("Dialog", "0"))
        self.label_50.setText(_translate("Dialog", "0"))
        self.label_51.setText(_translate("Dialog", "0"))
        self.label_52.setText(_translate("Dialog", "0"))
        self.label_53.setText(_translate("Dialog", "Премикс8203"))

